### PR TITLE
Add Cox

### PR DESCRIPTION
**Pull request by FJRubio67**
Add Cox

### CODE REVIEW

**Comment by FJRubio67** [comment]
Is it possible to indicate if a variable is a factor (categorical variable) automatically?

**Comment by lrnv** [comment]
Hum... I do not know, I will investigate.

**Review by lrnv — COMMENTED** [review]
Test ae passing now and the interface is working. We still have to write a bit of documentation on it

**Review by lrnv — COMMENTED** [review]
We should someday move to `Optimization.jl` to export as a user-tunable parameter the algorithm used to solve the numerical problem. In Cox, that would imply providing fast implementation (compliant with Optimization.jl's standard) of the nllh, but also of its gradient and eventually the hessian.

**Pull request merged**
